/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicTosRouteImport } from './routes/_public/tos'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedHomeRouteImport } from './routes/_protected/home'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/_admin'
import { Route as ProtectedAdminAdminIndexRouteImport } from './routes/_protected/_admin/admin.index'
import { Route as ProtectedAdminAdminUsersRouteImport } from './routes/_protected/_admin/admin.users'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTosRoute = PublicTosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHomeRoute = ProtectedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminAdminIndexRoute =
  ProtectedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminAdminUsersRoute =
  ProtectedAdminAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/home': typeof ProtectedHomeRoute
  '/profile': typeof ProtectedProfileRoute
  '/about': typeof PublicAboutRoute
  '/privacy': typeof PublicPrivacyRoute
  '/tos': typeof PublicTosRoute
  '/admin/users': typeof ProtectedAdminAdminUsersRoute
  '/admin/': typeof ProtectedAdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/home': typeof ProtectedHomeRoute
  '/profile': typeof ProtectedProfileRoute
  '/about': typeof PublicAboutRoute
  '/privacy': typeof PublicPrivacyRoute
  '/tos': typeof PublicTosRoute
  '/admin/users': typeof ProtectedAdminAdminUsersRoute
  '/admin': typeof ProtectedAdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_protected/_admin': typeof ProtectedAdminRouteWithChildren
  '/_protected/home': typeof ProtectedHomeRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/tos': typeof PublicTosRoute
  '/_public/': typeof PublicIndexRoute
  '/_protected/_admin/admin/users': typeof ProtectedAdminAdminUsersRoute
  '/_protected/_admin/admin/': typeof ProtectedAdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/profile'
    | '/about'
    | '/privacy'
    | '/tos'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/profile'
    | '/about'
    | '/privacy'
    | '/tos'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/_protected/_admin'
    | '/_protected/home'
    | '/_protected/profile'
    | '/_public/about'
    | '/_public/privacy'
    | '/_public/tos'
    | '/_public/'
    | '/_protected/_admin/admin/users'
    | '/_protected/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/tos': {
      id: '/_public/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof PublicTosRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_admin': {
      id: '/_protected/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_admin/admin/': {
      id: '/_protected/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminAdminIndexRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/_admin/admin/users': {
      id: '/_protected/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof ProtectedAdminAdminUsersRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
  }
}

interface ProtectedAdminRouteChildren {
  ProtectedAdminAdminUsersRoute: typeof ProtectedAdminAdminUsersRoute
  ProtectedAdminAdminIndexRoute: typeof ProtectedAdminAdminIndexRoute
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminAdminUsersRoute: ProtectedAdminAdminUsersRoute,
  ProtectedAdminAdminIndexRoute: ProtectedAdminAdminIndexRoute,
}

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren
  ProtectedHomeRoute: typeof ProtectedHomeRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedHomeRoute: ProtectedHomeRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicTosRoute: typeof PublicTosRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicTosRoute: PublicTosRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
