#!/usr/bin/env node
import { execSync } from 'child_process';
// Run once after cloning: node scripts/init.js
import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline/promises';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, '..');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const name = (await rl.question('Project name (kebab-case): ')).trim();
rl.close();

if (!/^[a-z][a-z0-9-]+$/.test(name)) {
  console.error('Invalid name. Use lowercase letters, numbers, and hyphens (e.g. my-project).');
  process.exit(1);
}

const OLD = 'scp-app';

// Files with scp-app references (source imports, config, README, package.json files)
const filesToUpdate = [
  'package.json',
  'apps/api/package.json',
  'packages/shared/package.json',
  'apps/api/src/routes/private/index.ts',
  'apps/api/src/db/user_queries.ts',
  'apps/api/src/plugins/cors.ts',
  'README.md',
];

console.log(`\nRenaming "${OLD}" → "${name}"...\n`);

for (const rel of filesToUpdate) {
  const filepath = path.join(root, rel);
  if (!fs.existsSync(filepath)) continue;
  const before = fs.readFileSync(filepath, 'utf8');
  const after = before.replaceAll(OLD, name);
  if (before !== after) {
    fs.writeFileSync(filepath, after);
    console.log(`  updated  ${rel}`);
  }
}

// Delete lockfile — package names changed, must regenerate
const lockfile = path.join(root, 'pnpm-lock.yaml');
if (fs.existsSync(lockfile)) {
  fs.unlinkSync(lockfile);
  console.log('  deleted  pnpm-lock.yaml (will be regenerated by pnpm install)');
}

// Reinitialize git
console.log('\nReinitializing git...');
execSync('rm -rf .git && git init && git add -A && git commit -m "Initial commit"', {
  cwd: root,
  stdio: 'inherit',
});

// Self-delete
fs.unlinkSync(__filename);
try {
  fs.rmdirSync(__dirname);
} catch {
  /* scripts/ not empty, leave it */
}

console.log(`\nDone! Project initialized as "${name}".`);
console.log('Next steps:');
console.log('  pnpm install');
console.log('  cp apps/api/.env.example apps/api/.env');
console.log('  cp apps/web/.env.example apps/web/.env');
console.log('  pnpm dev:api');
