#!/usr/bin/env node
// Run once after cloning: node scripts/init.js
import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline/promises';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, '..');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const name = (await rl.question('Project name (kebab-case): ')).trim();
rl.close();

if (!/^[a-z][a-z0-9-]+$/.test(name)) {
  console.error('Invalid name. Use lowercase letters, numbers, and hyphens (e.g. my-project).');
  process.exit(1);
}

const OLD = 'scp-app';

const SKIP_DIRS = new Set(['node_modules', '.git', 'dist', '.tanstack']);
const SKIP_FILES = new Set(['pnpm-lock.yaml']);

function* walkFiles(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (!SKIP_DIRS.has(entry.name)) yield* walkFiles(path.join(dir, entry.name));
    } else if (!SKIP_FILES.has(entry.name)) {
      yield path.join(dir, entry.name);
    }
  }
}

console.log(`\nRenaming "${OLD}" → "${name}"...\n`);

for (const filepath of walkFiles(root)) {
  let before;
  try {
    before = fs.readFileSync(filepath, 'utf8');
  } catch {
    continue; // skip binary files
  }
  if (!before.includes(OLD)) continue;
  const after = before.replaceAll(OLD, name);
  fs.writeFileSync(filepath, after);
  console.log(`  updated  ${path.relative(root, filepath)}`);
}

// Clear TOS content — specific to this template
const tosPath = path.join(root, 'apps/web/src/routes/tos.tsx');
if (fs.existsSync(tosPath)) {
  const tos = fs.readFileSync(tosPath, 'utf8');
  const updated = tos.replace(
    /<ol[\s\S]*?<\/ol>/,
    '<ol className="list-decimal space-y-3 pl-5">\n            {/* Add your terms here */}\n          </ol>',
  );
  if (updated !== tos) {
    fs.writeFileSync(tosPath, updated);
    console.log('  updated  apps/web/src/routes/tos.tsx (cleared terms list)');
  }
}

// Remove contact section from privacy policy — specific to this template's repo
const privacyPath = path.join(root, 'apps/web/src/routes/privacy.tsx');
if (fs.existsSync(privacyPath)) {
  const privacy = fs.readFileSync(privacyPath, 'utf8');
  const updated = privacy.replace(
    /\n\n\s+<section className="space-y-2">\s+<h2[^>]+>Contact<\/h2>[\s\S]*?<\/section>/,
    '',
  );
  if (updated !== privacy) {
    fs.writeFileSync(privacyPath, updated);
    console.log('  updated  apps/web/src/routes/privacy.tsx (removed contact section)');
  }
}

// Delete lockfile — package names changed, must regenerate
const lockfile = path.join(root, 'pnpm-lock.yaml');
if (fs.existsSync(lockfile)) {
  fs.unlinkSync(lockfile);
  console.log('  deleted  pnpm-lock.yaml (will be regenerated by pnpm install)');
}

// Copy .env.example → .env (skip if .env already exists)
for (const envExample of [
  path.join(root, 'apps/api/.env.example'),
  path.join(root, 'apps/web/.env.example'),
]) {
  const dest = envExample.replace('.env.example', '.env');
  if (!fs.existsSync(dest)) {
    fs.copyFileSync(envExample, dest);
    console.log(`  created  ${path.relative(root, dest)}`);
  }
}

// Self-delete
fs.unlinkSync(__filename);
try {
  fs.rmdirSync(__dirname);
} catch {
  /* scripts/ not empty, leave it */
}

console.log(`\nDone! Project initialized as "${name}".`);
console.log('Next steps:');
console.log('  1. Fill in apps/api/.env and apps/web/.env with your keys');
console.log('  2. pnpm install');
console.log('  3. pnpm dev');
