#!/usr/bin/env node
// Run once after cloning: node scripts/init.js
import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline/promises';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, '..');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const name = (await rl.question('Project name (kebab-case): ')).trim();
rl.close();

if (!/^[a-z][a-z0-9-]+$/.test(name)) {
  console.error('Invalid name. Use lowercase letters, numbers, and hyphens (e.g. my-project).');
  process.exit(1);
}

const OLD = 'scp-app';

const SKIP_DIRS = new Set(['node_modules', '.git', 'dist', '.tanstack']);
const SKIP_FILES = new Set(['pnpm-lock.yaml']);

function* walkFiles(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (!SKIP_DIRS.has(entry.name)) yield* walkFiles(path.join(dir, entry.name));
    } else if (!SKIP_FILES.has(entry.name)) {
      yield path.join(dir, entry.name);
    }
  }
}

console.log(`\nRenaming "${OLD}" → "${name}"...\n`);

for (const filepath of walkFiles(root)) {
  let before;
  try {
    before = fs.readFileSync(filepath, 'utf8');
  } catch {
    continue; // skip binary files
  }
  if (!before.includes(OLD)) continue;
  const after = before.replaceAll(OLD, name);
  fs.writeFileSync(filepath, after);
  console.log(`  updated  ${path.relative(root, filepath)}`);
}

// Replace homepage with minimal template
const indexPath = path.join(root, 'apps/web/src/routes/index.tsx');
if (fs.existsSync(indexPath)) {
  const homepage = `import { createFileRoute } from '@tanstack/react-router';
import { PageLayout } from '@/components/PageLayout';

export const Route = createFileRoute('/')({
  component: Index,
});

function Index() {
  return (
    <PageLayout className="items-center justify-center">
      ${name}
    </PageLayout>
  );
}
`;
  fs.writeFileSync(indexPath, homepage);
  console.log('  updated  apps/web/src/routes/index.tsx (replaced with minimal template)');
}

// Replace about page with minimal template
const aboutPath = path.join(root, 'apps/web/src/routes/about.tsx');
if (fs.existsSync(aboutPath)) {
  const about = `import { createFileRoute } from '@tanstack/react-router';
import { PageLayout } from '@/components/PageLayout';

export const Route = createFileRoute('/about')({
  component: About,
});

function About() {
  return (
    <PageLayout className="items-center justify-center">
      <h1 className="text-4xl font-bold">about</h1>
    </PageLayout>
  );
}
`;
  fs.writeFileSync(aboutPath, about);
  console.log('  updated  apps/web/src/routes/about.tsx (replaced with minimal template)');
}

// Replace TOS with minimal template
const tosPath = path.join(root, 'apps/web/src/routes/tos.tsx');
if (fs.existsSync(tosPath)) {
  const tos = `import { createFileRoute } from '@tanstack/react-router';
import { PageLayout } from '@/components/PageLayout';

export const Route = createFileRoute('/tos')({
  component: Tos,
});

function Tos() {
  return (
    <PageLayout className="px-6 py-16">
      <div className="mx-auto w-full max-w-2xl">
        <h1 className="mb-8 text-2xl font-bold">Terms of Service</h1>
      </div>
    </PageLayout>
  );
}
`;
  fs.writeFileSync(tosPath, tos);
  console.log('  updated  apps/web/src/routes/tos.tsx (replaced with minimal template)');
}

// Replace privacy policy with minimal template
const privacyPath = path.join(root, 'apps/web/src/routes/privacy.tsx');
if (fs.existsSync(privacyPath)) {
  const privacy = `import { createFileRoute } from '@tanstack/react-router';
import { PageLayout } from '@/components/PageLayout';

export const Route = createFileRoute('/privacy')({
  component: Privacy,
});

function Privacy() {
  return (
    <PageLayout className="px-6 py-16">
      <div className="mx-auto w-full max-w-2xl">
        <h1 className="mb-8 text-2xl font-bold">Privacy Policy</h1>
      </div>
    </PageLayout>
  );
}
`;
  fs.writeFileSync(privacyPath, privacy);
  console.log('  updated  apps/web/src/routes/privacy.tsx (replaced with minimal template)');
}

// Delete lockfile — package names changed, must regenerate
const lockfile = path.join(root, 'pnpm-lock.yaml');
if (fs.existsSync(lockfile)) {
  fs.unlinkSync(lockfile);
  console.log('  deleted  pnpm-lock.yaml (will be regenerated by pnpm install)');
}

// Copy .env.example → .env (skip if .env already exists)
for (const envExample of [
  path.join(root, 'apps/api/.env.example'),
  path.join(root, 'apps/web/.env.example'),
]) {
  const dest = envExample.replace('.env.example', '.env');
  if (!fs.existsSync(dest)) {
    fs.copyFileSync(envExample, dest);
    console.log(`  created  ${path.relative(root, dest)}`);
  }
}

// Install
let installOk = true;
try {
  execSync('pnpm install', { cwd: root, stdio: 'inherit' });
} catch {
  installOk = false;
  console.warn('  warning  pnpm install failed');
}

// Format (only if install succeeded)
if (installOk) {
  try {
    execSync('pnpm fmt', { cwd: root, stdio: 'inherit' });
  } catch {
    console.warn('  warning  pnpm fmt failed, skipping');
  }
}

// Self-delete
fs.unlinkSync(__filename);
try {
  fs.rmdirSync(__dirname);
} catch {
  /* scripts/ not empty, leave it */
}

console.log(`\nDone! Project initialized as "${name}".`);
console.log('Next steps:');
console.log('  1. Fill in apps/api/.env and apps/web/.env with your keys');
if (installOk) {
  console.log('  2. pnpm dev');
} else {
  console.log('  2. pnpm install');
  console.log('  3. pnpm dev');
}
